# Generated by Django 3.2.5 on 2021-07-08 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_to_do', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='title',
            new_name='task',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='description',
        ),
    ]
